import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google"
import "./globals.css";

const fontSans = Bricolage_Grotesque({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = React.PropsWithChildren

export default function RootLayout({
  children,
}: Readonly<Props>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
